:PROPERTIES:
:ID:       85dbb503-401c-42c9-a23e-22dcba20d5ea
:END:
#+title: Cryptography
* What is Cryptography?
  Cryptography literally means "secret writing". Historically it was used for
  secure communications, and retains this use to this day. Other applications
  include data authentication (ensure a message actually comes from a claimant)
  and data integrity (ensure a message is unchanged). Cryptography is used
  /everywhere/ on the internet nowadays - HTTPS, SSH, media encryption, and more
  are all used day to day. In modern cryptography, [[id:a5936704-e256-4969-8d91-31247eac77eb][Security]] is formalized rather
  than reliant upon a fuzzy trial-and-error approach to checking. 

  Cryptography takes place between two parties, a sender (S), often known as
  Alice, and a receiver (R) often known as Bob. An adversary (A), or Eve, wants
  to intercept the public communication between S and R and recover the original
  message.

  There are two main types of cryptography: [[id:2751619a-5b7f-4e75-9d08-253fdce24b90][Symmetric Key Encryption]] and
  asymmetric key encryption.
  
* Symmetric Key Encryption
  :PROPERTIES:
  :ID:       2751619a-5b7f-4e75-9d08-253fdce24b90
  :END:
  Symmetric key encryption, also known as secret key encryption, relies on a
  single key, K, shared between the sender and receiver. We use the IND-CPA
  definition of security for these types of schemes (see [[id:a5936704-e256-4969-8d91-31247eac77eb][Security]]). 

  For a symmetric scheme, we use the following notation:
  - $MsgSp$: what messages are encryptable?
  - $KeySp$: what keys are allowed?
    - Alternatively, $K$: the key generation algorithm
  - $E$: the encryption algorithm
  - $D$: the decryption algorithm

  In such a scheme, the following is required:

  For all $M$ in $MsgSp$ and all $K$ in $KeySp$ (or generated):
  $D(K, E(K, M)) = M$

  Plainly put, for every message and every key, decrypting an encrypted message
  with the same key used for encryption should yield the original message.

  Notation: $C$ is the ciphertext generated by $E(K, M)$.

  [[id:6a0014d8-81bb-4eb2-85d1-d963559af47e][Block Ciphers]] are the building blocks of symmetric encryption.

  Examples:
  - [[id:68f75ded-cdb1-45e6-bbe7-0b908dc4722e][One Time Pad]]

    
