:PROPERTIES:
:ID:       85dbb503-401c-42c9-a23e-22dcba20d5ea
:END:
#+title: Cryptography
* What is Cryptography?
  Cryptography literally means "secret writing". Historically it was used for
  secure communications, and retains this use to this day. Other applications
  include data authentication (ensure a message actually comes from a claimant)
  and data integrity (ensure a message is unchanged). Cryptography is used
  /everywhere/ on the internet nowadays - HTTPS, SSH, media encryption, and more
  are all used day to day. In modern cryptography, [[id:1215c93b-00ed-4a79-a1f9-5e1ae557fb1c][Security]] is formalized rather
  than reliant upon a fuzzy trial-and-error approach to checking. 

  Cryptography takes place between two parties, a sender (S), often known as
  Alice, and a receiver (R) often known as Bob. An adversary (A), or Eve, wants
  to intercept the public communication between S and R and recover the original
  message.

  There are two main types of cryptography: [[id:2751619a-5b7f-4e75-9d08-253fdce24b90][Symmetric Key Encryption]] and
  asymmetric key encryption.
  
* Symmetric Key Encryption
  :PROPERTIES:
  :ID:       2751619a-5b7f-4e75-9d08-253fdce24b90
  :END:
  Symmetric key encryption, also known as secret key encryption, relies on a
  single key, K, shared between the sender and receiver.

  For a symmetric scheme, we use the following notation:
  - $MsgSp$: what messages are encryptable?
  - $KeySp$: what keys are allowed?
    - Alternatively, $K$: the key generation algorithm
  - $E$: the encryption algorithm
  - $D$: the decryption algorithm

  In such a scheme, the following is required:

  For all $M$ in $MsgSp$ and all $K$ in $KeySp$ (or generated):
  $D(K, E(K, M)) = M$

  Plainly put, for every message and every key, decrypting an encrypted message
  with the same key used for encryption should yield the original message.

  Notation: $C$ is the ciphertext generated by $E(K, M)$.

  An example of symmetric key encryption is the [[id:88a57ecc-9439-4653-be92-8b4ad7769753][One Time Pad]].

* Security
  :PROPERTIES:
  :ID:       1215c93b-00ed-4a79-a1f9-5e1ae557fb1c
  :END:

  Informally, the ciphertext of an encryption scheme shouldn't give any
  new information to attackers.

  *Perfect Security*: a symmetric encryption scheme $SE$ is perfectly secure (or
   *Shannon secure*) if for every ciphertext $C$ and messages $M_1$ and $M_2$,

   $P[E(K, M_1) = C] = P[E(K, M_2) = C]$

   Essentially, for any ciphertext, all messages are equally likely.

   The [[id:88a57ecc-9439-4653-be92-8b4ad7769753][One Time Pad]] is perfectly secure.

* One Time Pad
  :PROPERTIES:
  :ID:       88a57ecc-9439-4653-be92-8b4ad7769753
  :END:

  The One Time Pad is an example of a perfect encryption scheme. Unfortunately,
  the unwieldiness of the key makes it a poor choice for practical usage. It is,
  however, very simple.

  - $MsgSp = \{0, 1\}^n$
  - $KeySp = \{0, 1\}^n$ - a key is picked uniformly at random.
  - $E(K, M) = C \leftarrow K \oplus M$
  - $D(K, C) = M \leftarrow K \oplus C$

  Aside: this works because $k \oplus k = 0$, covering the encryption and
  decryption phases together, and $m \oplus 0 = m$.

** Proof of Security
   1) Fix any ciphertext $C \in \{0, 1\}^n$
   2) By the definition of the encryption algorithm, we have that for all $M$,
      $P[E(K, M) = C] = P[K \oplus M = C] = P[K \oplus (M \oplus M) = C \oplus
      M] = P[K = C \oplus M]$
   3) $K$ is chosen at random from $2^n$ possible keys (the size of the key
      space), so $P[K = C \oplus M] = \frac{1}{2^n}$
   4) This holds for every $M$, so for any ciphertext, all $M$s are equally
      likely to emit from decrypting $C$.
     
** Shannon's Theorem (Optimality of One Time Pads)
   Goal: if a scheme $(K, E, D)$ is Shannon secure, then $|KeySp|$ can't be smaller than
   $|MsgSp|$.
   
   1) Fix $C$ by picking $M$ and $K$. $C = E(K, M)$.
      - Across all $K$, $P[E(K, M) = C] > 0$ because of the construction of $C$.
   2) Assume that there exists $M_2$ such that $\forall K, P[D(K, C) = M_2] = 0$
      - This implies that $C$ never decrypts to $M_2$.
      - This also implies that the message space is larger than the key space.
   3) By the correctness of symmetric encryption, (2) means that $\forall K,
      P[E(K, M_2) = C] = 0$.
   4) *CONTRADICTION*: This scheme is Shannon secure, but $P[E(K, M) = C] \neq
      P[E(K, M_2) = C]$.
   5) Therefore, our assumption that such an $M_2$ exists is false, and we have:
      $\forall M_2 \in MsgSp,\, \exists K' \;.\; D(K', C) = M_2$.
   6) Furthermore, we have $|KeySp| \geq |MsgSp|$ because there can't be any
      messages that can't be encrypted to a ciphertext by a key.

   As a consequence of Shannon's Theorem, we know that the
   information-theoretic approach to cryptography is impractical. Instead, we
   relax the need for perfect security and guarantee security for X number of
   years under certain computational bounds. This is known as
   *computational-complexity cryptography*. This approach assumes the existence
   of computationally hard problems, and requires keys to remain secret.

   
